---
- name: install the package
  hosts: windows2
  become: false
  tasks:
    - name: update the system
      win_updates:
        category_names:
         - SecurityUpdates
        state: searched
        log_path: C:\ansible_wu.txt
 

